name: every_door
description: Next generation OpenStreetMap amenity mapper

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Also update version in constants.dart!
version: 3.1.0+34

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: "^3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  geolocator: ^9.0.1
  sensors_plus: ^2.0.5
  http: ^0.13.3
  flutter_map: ^2.1.0
  latlong2: ^0.8.1
  sqflite: ^2.0.0+3
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^8.0.0
  flutter_riverpod: ^2.3.0
  proximity_hash: ^2.0.0
  diacritic: ^0.1.3
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.0
  adaptive_dialog: ^1.9.0-0
  xml: ^6.3.0
  country_coder: ^1.1.0
  settings_ui: ^2.0.2
  uuid: ^3.0.6
  archive: ^3.1.6
  phone_numbers_parser: ^4.2.0
  line_icons: ^2.0.1
  share_plus: ^6.3.4
  path_provider: ^2.0.9
  path: ^1.8.1
  responsive_grid_list: ^1.2.3
  url_launcher: ^6.0.20
  flutter_dropdown_alert: ^1.0.3
  oauth2_client: ^3.0.0
  device_info_plus: ^8.2.2
  unorm_dart: ^0.2.0
  logging: ^1.0.2
  encrypt: ^5.0.1
  flutter_markdown: ^0.6.10+2
  path_drawing: ^1.0.0

# Uncomment this for publishing on F-Droid
#fdependency_overrides:
#f  geolocator_android:
#f    git:
#f      url: https://github.com/Zverik/flutter-geolocator.git
#f      ref: floss
#f      path: geolocator_android

dev_dependencies:
  test: ^1.24.1
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/presets.db
    - assets/lets-encrypt-r3.pem
    - assets/roofs/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "icon/app_icon.png"
