name: every_door
description: Next generation OpenStreetMap amenity mapper

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Also update version in constants.dart!
version: 0.5.0+19

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  geolocator: ^8.0.0
  # location: ^4.4.0
  http: ^0.13.3
  flutter_map: ^1.0.0
  sqflite: ^2.0.0+3
  shared_preferences: ^2.0.7
  flutter_riverpod: ^1.0.1
  proximity_hash: ^2.0.0
  diacritic: ^0.1.3
  cached_network_image: ^3.1.0
  adaptive_dialog: ^1.1.0
  xml: ^5.3.1
  country_coder: ^1.1.0
  settings_ui: ^2.0.2
  uuid: ^3.0.5
  archive: ^3.1.6
  phone_numbers_parser: ^4.2.0
  line_icons: ^2.0.1
  share_plus: ^4.0.4
  path_provider: ^2.0.9
  responsive_grid_list: ^1.2.3
  url_launcher: ^6.0.20
  flutter_dropdown_alert: ^1.0.3
  oauth2_client: ^2.3.3
  device_info_plus: ^3.2.2
  unorm_dart: ^0.2.0
  logging: ^1.0.2
  encrypt: ^5.0.1

dev_dependencies:
  test: ^1.19.5
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/presets.db
    - assets/lets-encrypt-r3.pem
    - assets/roofs/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "icon/app_icon.png"