name: APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
      - run: flutter config --no-analytics
      - run: flutter upgrade

      - name: Cache
        id: cache-presets
        uses: pat-s/always-upload-cache@v3.0.1
        with:
          path: assets/presets.db
          key: presets

      - name: download & unzip
        if: steps.cache-presets.outputs.cache-hit != 'true'
        run: |
          wget -q https://taginfo.openstreetmap.org/download/taginfo-db.db.bz2
          bzip2 -d taginfo-db.db.bz2

      - name: generate presets.db
        if: steps.cache-presets.outputs.cache-hit != 'true'
        run: cd tools && ./update.sh ../taginfo-db.db && cd ..

      - env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
        run: echo -n $KEY_JKS | base64 -d > android/key.jks

      - run: flutter pub get

      - env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        run: flutter build apk --release

      - uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 1
  create_release:
    name: "Prelease"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: app-release.apk
